name: APK

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  assemble_demo_apk:
    name: Assemble ${{ matrix.variant }} APK
    runs-on: ubuntu-latest
    strategy:
        matrix:
            variant: [Demo, Debug]
    steps:
      - name: Checkout GIT
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Build ${{ matrix.variant }} APK
        run: ./gradlew assemble${{ matrix.variant }}

      - name: Lowercase Variant
        run: |
          VARIANT="${{ matrix.variant }}"
          echo "LOWERCASE_VARIANT=${VARIANT@L}" >> $GITHUB_ENV

      - name: Upload ${{ matrix.variant }} APK to Github Actions
        uses: actions/upload-artifact@v4
        with:
          name: Ivy-Wallet-${{ matrix.variant }}.apk
          path: app/build/outputs/apk/${{ env.LOWERCASE_VARIANT }}/app-${{ env.LOWERCASE_VARIANT }}.apk
