name: Build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Fix GitHub Actions crashing with:
    # CRASH: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=1g"

    steps:
      - name: Checkout GIT
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
      #----------------------------------------------------

      #Optimization
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4
      #---------------------------------------------------

      # RUN
      - name: Build demo APK
        run: ./gradlew assembleDemo

      - name: Upload Ivy Wallet APK
        uses: actions/upload-artifact@v4
        with:
          name: Ivy-Wallet-Demo.apk
          path: app/build/outputs/apk/demo/app-demo.apk
      #------------------------------------------------------------------
